<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@taglib uri="/struts-tags" prefix="s" %>
<!DOCTYPE html>

<html>
<head>
    <!-- main -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="wayne">

    <title>CT Repository</title>
    <!-- css -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap3.css">
    <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="css/repository.css">

    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Allerta">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Berkshire+Swash">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap3.js"></script>
</head>


<%@ page import="java.util.*" %>
<%@ page import="java.sql.*" %>
<%
    // search table paper
    Class.forName("com.mysql.jdbc.Driver").newInstance();
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/paper", "root", "123456");
    Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    String sql = "select * from paper.list";
    ResultSet rs = stmt.executeQuery(sql);
    //获取记录总数
    rs.last();
    int RowCount = rs.getRow();
%>

<body>
<!-- Wrap all page content here -->
<div id="wrap">
    <!-- top navigation -->
    <jsp:include page="template_top.jsp"/>

    <div class="container">
        <!-- main unit -->
        <div class="hero-unit">
            <h1>Combinatorial Testing Repository</h1>

            <p>Combinatorial Testing (CT) can detect failures triggered by interactions of parameters
                in the Software Under Test (SUT) with a covering array test suite generated by some sampling
                mechanisms. It has been an active field of research in the last twenty years.
            </p>
            <button class="btn btn-lg btn-success pull-right" onClick="location.href='../search.jsp'">
                Enter the Repository &raquo;</button>
        </div>

        <!-- description -->
        <div class="row">
            <div class="col-md-3">
                <h3 class="mycenter"><a href="#"><i class="icon-globe icon-4x"></i></a></h3>
                <h3>Publication</h3>
                <p>all research papers in this area are collected</p>
            </div>

            <div class="col-md-3">
                <h3 class="mycenter"><a href="#"><i class="icon-bar-chart icon-4x"></i></a></h3>
                <h3>Statistic</h3>
                <p>the line and pie charts to show the trend</p>
            </div>

            <div class="col-md-3">
                <h3 class="mycenter"><a href="#"><i class="icon-group icon-4x"></i></a></h3>
                <h3>List</h3>
                <p>author, field, and publication lists are provided</p>
            </div>

            <div class="col-md-3">
                <h3 class="mycenter"><a href="#"><i class="icon-book icon-4x"></i></a></h3>
                <h3>Cite</h3>
                <p>abstract and bibTex citations are available for all papers</p>
            </div>
        </div>

    </div><!-- /container -->

    <div id="push"></div>
</div><!-- /wrap -->

<!-- footer -->
<jsp:include page="template_bottom.jsp"/>

</body>
</html>